apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: global
  namespace: gateway
  labels:
spec:
  gatewayClassName: istio
  listeners:
  - name: tcp-5432
    port: 5432
    protocol: TCP
    allowedRoutes:
      kinds:
      - kind: TCPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: immudb
  - name: grpc-3322
    port: 3322
    protocol: HTTPS
    allowedRoutes:
      kinds:
      - kind: GRPCRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: immudb
  - name: grpc-3334
    port: 3334
    protocol: HTTPS
    allowedRoutes:
      kinds:
      - kind: GRPCRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: immudb
  - protocol: HTTP
    port: 8080
    name: immudb-admin
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            kubernetes.io/metadata.name: immudb
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: immudb-postgres
  namespace: immudb
spec:
  parentRefs:
  - name: global
    namespace: gateway
  rules:
  - backendRefs:
    - name: rw
      namespace: immudb
      port: 5432
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-3322
  namespace: immudb
spec:
  parentRefs:
    - name: global
      namespace: gateway
  rules:
  - backendRefs:
    - name: rw
      namespace: immudb
      port: 3322
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-3334
  namespace: immudb
spec:
  parentRefs:
    - name: global
      namespace: gateway
  rules:
  - backendRefs:
    - name: ro
      namespace: immudb
      port: 3334
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immudb-admin
  namespace: immudb
spec:
  parentRefs:
    - name: global
      namespace: gateway
  rules:
  - backendRefs:
    - name: rw
      namespace: immudb
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immudb-console
  namespace: immudb
spec:
  parentRefs:
    - name: global
      namespace: gateway
  rules:
  - backendRefs:
    - name: console
      namespace: immudb
      port: 9090
