apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# The stable channel doesn't include TCPRoutes
# - "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.1.0"
resources:
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml
- istio.yaml
- kiali.yaml
- prometheus.yaml
- namespace.yaml
- gateway.yaml
- gateway-ns.yaml
