apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immudb
resources:
- namespace.yaml
- configmap.yaml
- service.yaml
- statefulset.yaml
images:
- name: codenotary/immudb
  newName: codenotary/immudb
  newTag: 1.9.4
