apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- service.yaml
- statefulset.yaml
- audit.yaml
images:
- name: codenotary/immudb
  newName: codenotary/immudb
  newTag: 1.9.5
- name: codenotary/immuclient
  newName: codenotary/immuclient
  newTag: 1.9.5
