# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: immudb
  labels:
    app: immudb
spec:
  ports:
  - name: grpc
    port: 3322
  - name: postgres
    port: 5432
  clusterIP: None
  selector:
    app: immudb
---
# Client service for connecting to any immudb instance for reads.
# For writes, you must instead connect to the primary: immudb-0.immudb.
apiVersion: v1
kind: Service
metadata:
  name: immudb-read
  labels:
    app: immudb
spec:
  ports:
  - name: grpc
    port: 3334
  - name: postgres
    port: 5432
  clusterIP: None
  selector:
    app: immudb
---
# immudb master webserver (read/write)
apiVersion: v1
kind: Service
metadata:
  name: immudb-webserver
  labels:
    app: immudb
spec:
  ports:
  - name: webadmin
    port: 8080
  selector:
    statefulset.kubernetes.io/pod-name: immudb-0
---
# immudb replica webserver (read-only)
apiVersion: v1
kind: Service
metadata:
  labels:
    app: immudb
  name: immudb-ext
spec:
  ports:
    - name: webread
      port: 9090
  selector:
    statefulset.kubernetes.io/pod-name: immudb-2b
